src/Entity/Localisations.php
<?php

namespace App\Entity;

use App\Repository\LocalisationsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LocalisationsRepository::class)]
class Localisations
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $n_voie = null;

    #[ORM\Column(length: 100)]
    private ?string $type_voie = null;

    #[ORM\Column(length: 100)]
    private ?string $nom_voie = null;

    #[ORM\Column(length: 255)]
    private ?string $villes = null;

    #[ORM\Column]
    private ?int $codepostales = null;

    #[ORM\Column(length: 100)]
    private ?string $region = null;

    #[ORM\OneToMany(mappedBy: 'localisation', targetEntity: Propertys::class)]
    private Collection $propertys;

    public function __construct()
    {
        $this->propertys = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNVoie(): ?int
    {
        return $this->n_voie;
    }

    public function setNVoie(int $n_voie): static
    {
        $this->n_voie = $n_voie;

        return $this;
    }

    public function getTypeVoie(): ?string
    {
        return $this->type_voie;
    }

    public function setTypeVoie(string $type_voie): static
    {
        $this->type_voie = $type_voie;

        return $this;
    }

    public function getNomVoie(): ?string
    {
        return $this->nom_voie;
    }

    public function setNomVoie(string $nom_voie): static
    {
        $this->nom_voie = $nom_voie;

        return $this;
    }

    public function getVilles(): ?string
    {
        return $this->villes;
    }

    public function setVilles(string $villes): static
    {
        $this->villes = $villes;

        return $this;
    }

    public function getCodepostales(): ?int
    {
        return $this->codepostales;
    }

    public function setCodepostales(int $codepostales): static
    {
        $this->codepostales = $codepostales;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): static
    {
        $this->region = $region;

        return $this;
    }

    /**
     * @return Collection<int, Propertys>
     */
    public function getPropertys(): Collection
    {
        return $this->propertys;
    }

    public function addProperty(Propertys $property): static
    {
        if (!$this->propertys->contains($property)) {
            $this->propertys->add($property);
            $property->setLocalisation($this);
        }

        return $this;
    }

    public function removeProperty(Propertys $property): static
    {
        if ($this->propertys->removeElement($property)) {
            // set the owning side to null (unless already changed)
            if ($property->getLocalisation() === $this) {
                $property->setLocalisation(null);
            }
        }

        return $this;
    }
}

src/Form/LocalisationsType.php
<?php

namespace App\Form;

use App\Entity\Localisations;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LocalisationsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('n_voie')
            ->add('type_voie')
            ->add('nom_voie')
            ->add('villes')
            ->add('codepostales')
            ->add('region')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Localisations::class,
        ]);
    }
}

src/Controller/LocalisationsController.php
<?php

namespace App\Controller;

use App\Entity\Localisations;
use App\Form\LocalisationsType;
use App\Repository\LocalisationsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/localisations')]
class LocalisationsController extends AbstractController
{
    #[Route('/', name: 'app_localisations_index', methods: ['GET'])]
    public function index(LocalisationsRepository $localisationsRepository): Response
    {
        return $this->render('localisations/index.html.twig', [
            'localisations' => $localisationsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_localisations_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $localisation = new Localisations();
        $form = $this->createForm(LocalisationsType::class, $localisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($localisation);
            $entityManager->flush();

            return $this->redirectToRoute('app_localisations_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('localisations/new.html.twig', [
            'localisation' => $localisation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_localisations_show', methods: ['GET'])]
    public function show(Localisations $localisation): Response
    {
        return $this->render('localisations/show.html.twig', [
            'localisation' => $localisation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_localisations_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Localisations $localisation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LocalisationsType::class, $localisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_localisations_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('localisations/edit.html.twig', [
            'localisation' => $localisation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_localisations_delete', methods: ['POST'])]
    public function delete(Request $request, Localisations $localisation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$localisation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($localisation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_localisations_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/localisations/_delete_form.html.twig
<form method="post" action="{{ path('app_localisations_delete', {'id': localisation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ localisation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/localisations/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/localisations/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Localisations{% endblock %}

{% block body %}
    <h1>Edit Localisations</h1>

    {{ include('localisations/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_localisations_index') }}">back to list</a>

    {{ include('localisations/_delete_form.html.twig') }}
{% endblock %}

templates/localisations/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Localisations index{% endblock %}

{% block body %}
    <h1>Localisations index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>N_voie</th>
                <th>Type_voie</th>
                <th>Nom_voie</th>
                <th>Villes</th>
                <th>Codepostales</th>
                <th>Region</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for localisation in localisations %}
            <tr>
                <td>{{ localisation.id }}</td>
                <td>{{ localisation.nVoie }}</td>
                <td>{{ localisation.typeVoie }}</td>
                <td>{{ localisation.nomVoie }}</td>
                <td>{{ localisation.villes }}</td>
                <td>{{ localisation.codepostales }}</td>
                <td>{{ localisation.region }}</td>
                <td>
                    <a href="{{ path('app_localisations_show', {'id': localisation.id}) }}">show</a>
                    <a href="{{ path('app_localisations_edit', {'id': localisation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_localisations_new') }}">Create new</a>
{% endblock %}

templates/localisations/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Localisations{% endblock %}

{% block body %}
    <h1>Create new Localisations</h1>

    {{ include('localisations/_form.html.twig') }}

    <a href="{{ path('app_localisations_index') }}">back to list</a>
{% endblock %}

templates/localisations/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Localisations{% endblock %}

{% block body %}
    <h1>Localisations</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ localisation.id }}</td>
            </tr>
            <tr>
                <th>N_voie</th>
                <td>{{ localisation.nVoie }}</td>
            </tr>
            <tr>
                <th>Type_voie</th>
                <td>{{ localisation.typeVoie }}</td>
            </tr>
            <tr>
                <th>Nom_voie</th>
                <td>{{ localisation.nomVoie }}</td>
            </tr>
            <tr>
                <th>Villes</th>
                <td>{{ localisation.villes }}</td>
            </tr>
            <tr>
                <th>Codepostales</th>
                <td>{{ localisation.codepostales }}</td>
            </tr>
            <tr>
                <th>Region</th>
                <td>{{ localisation.region }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_localisations_index') }}">back to list</a>

    <a href="{{ path('app_localisations_edit', {'id': localisation.id}) }}">edit</a>

    {{ include('localisations/_delete_form.html.twig') }}
{% endblock %}